[package]
name = "turnstile"
version = "0.1.0"
authors = ["Christian Wood <cwood@tpt.org>"]
edition = "2018"

[dependencies]
reqwest = "^0.11.3"
structopt = "0.3.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
